backend:
  name: git-gateway
  branch: master

media_folder: "assets/images/uploads"

collections:
  - label: "Data"
    name: "data"
    files:
      - label: "Menú principal"
        name: "menu"
        file: "_data/menu.yml"
        fields:
          - label: Items
            name: items
            widget: "list"
            fields:
              - {label: "Language", name: "language", widget: "select", options: ["eu", "es"]}
              - label: Item
                name: item
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Url, name: url, widget: string}
                  - label: "Sub menu"
                    name: "submenu"
                    widget: "list"
                    fields:
                      - {label: Title, name: title, widget: string}
                      - label: Item
                        name: item
                        widget: list
                        fields:
                          - {label: Title, name: title, widget: string}
                          - {label: Url, name: url, widget: string}

  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Featured Image"
        name: "image"
        widget: "object"
        fields:
          - {label: "Imagen", name: "url", widget: "image"}
          - {label: "Alt", name: "alt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "enlaces"
    label: "Enlaces Euskera"
    folder: "content/_enlaces/eu"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Language", name: "language", widget: "select", options: ["eu", "es"]}
      - {label: "Link", name: "link", widget: "string"}
      - label: "Imagen"
        name: "image"
        widget: "object"
        fields:
          - {label: "Imagen", name: "url", widget: "image"}
          - {label: "Alt", name: "alt", widget: "string"}
